# 项目的启动端口
server:
  port: 20000
spring:
  application:
    # 定义项目名称
    name: coupon-template-serv
  datasource:
    # mysql数据源
    url: jdbc:mysql://rm-cn-4xl3e1zjr00016fo.rwlb.rds.aliyuncs.com:3306/db_coupon?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: Jcx@@123
    # 指定数据源DataSource类型
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接池参数配置，比如池子大小、超时时间、是否自动提交等等
    hikari:
      pool-name: CloudCouponHikari
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 60000
      auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      # 在生产环境全部为none，防止ddl结构被自动执行，破坏生产数据
      ddl-auto: none
    # 在日志中打印经过格式化的SQL语句
#    properties:
#      hibernate.format_sql: true
#      hibernate.show_sql: true
    open-in-view: false
  cloud:
    nacos:
      discovery:
        # nacos服务地址，可以配置多个，逗号分割
        server-addr: localhost:8848
        # 注册到nacos的服务名
        service: coupon-template-serv
        # 各个微服务向nacos发送心跳的间隔，单位 毫秒
        heart-beat-interval: 5000
        # 超时时间，大于发送间隔
        heart-beat-timeout: 20000
        # 元数据，可选
        metadata:
          myData: abc
        # nacos创建的命名空间的 ID
        namespace: dev
        # 本地配置即可，同一个命名空间且同一分组下的服务才能相互调用
        group: myGroup
        # 可选默认true，如果不提供服务，可以选false
        register-enabled: true
        # 服务宕机后，是否优先从本地读取服务配置
        naming-load-cache-at-start: false
    sleuth:
      sampler:
        # 采样率，0-1的浮点数，如果小于 1，表示 有的请求不会被采样
        probability: 1
        # 每秒有多少个请求进行采样
        rate: 1000
    zipkin:
      sender:
        type: web
        base-url: http://localhost:9411/